# Generated by Django 2.0.9 on 2019-01-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0008_auto_20181115_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='redirect_uri',
            field=models.CharField(max_length=1024),
        ),
    ]
